services:
  hayoung-place:
    container_name: springboot
    image: api-server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    env_file:
      - backend/.env.docker
    networks:
      - backend

networks:
  backend:
    driver: bridge
