services:
  hayoung-place:
    container_name: springboot
    image: api-server
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "5000:5000"
    depends_on:
      - redis
    env_file:
      - .env.docker
    networks:
      - backend


  redis:
    container_name: redis
    image: redis:6.2
    command: [ "redis-server", "--requirepass", "${REDIS_PASSWORD}" ]
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    networks:
      - backend

networks:
  backend:
    driver: bridge

volumes:
  redis-data:
