server:
  port: 5000

spring:
  application:
    name: hayoung-place
  config:
    import: optional:file:backend/.env.local[.properties]
  cloud:
    aws:
      credentials:
        access-key: ${AWS_ACCESS_KEY}
        secret-key: ${AWS_SECRET_KEY}
      region:
        static: ${AWS_REGION}
      s3:
        bucket: ${AWS_S3_BUCKET}
  data:
    redis:
      host: ${REDIS_HOST}
      port: ${REDIS_PORT}
      password: ${REDIS_PASSWORD}
      database: ${REDIS_DATABASE}
    mongodb:
      uri: ${MONGO_URI}

  security:
    oauth2:
      client:
        registration:
          google:
            provider: google
            client-name: Google
            client-id: ${GOOGLE_CLIENT_ID}
            client-secret: ${GOOGLE_CLIENT_SECRET}
            redirect-uri: ${GOOGLE_URL}
            scope:
              - email
              - profile
            authorization-grant-type: authorization_code

springdoc:
  swagger-ui:
    operations-sorter: method
    display-request-duration: true
    persist-authorization: true
  api-docs:
    path: /v3/api-docs
  default-produces-media-type: application/json

swagger:
  servers:
    local: ${SWAGGER_SERVER_LOCAL}
    prod: ${SWAGGER_SERVER_PROD}

cors:
  allowed-origins:
    - ${CORS_ALLOWED_ORIGINS}

jwt:
  secret: ${JWT_SECRET}
  access-token-expired: ${JWT_ACCESS_TOKEN_EXPIRED}
  refresh-token-expired: ${JWT_REFRESH_TOKEN_EXPIRED}

app:
  frontend-url: ${FRONTEND_URL}

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.data.mongodb: DEBUG
    org.springframework.security: DEBUG
    com.millo.hayoungplace: DEBUG
