name: CD to AWS

on:
  push:
    branches:
      - main
    paths:
      - 'backend/**'

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Copy backend project to AWS server
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          source: "backend"
          target: "/home/ec2-user/hayoung-place"
          rm: true
          strip_components: 1
          exclude: |
            .git/
            .github/
            build/
            .env

      - name: Create .env on AWS server
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/hayoung-place
            echo "${{ secrets.ENV }}" | base64 --decode > .env
            echo ".env created"

      - name: Deploy with Docker Compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.AWS_HOST }}
          username: ec2-user
          key: ${{ secrets.AWS_SSH_KEY }}
          port: 22
          script: |
            cd /home/ec2-user/hayoung-place
            docker-compose down || true
            docker-compose --env-file .env up -d --build
            echo "Deployment complete!"
